package it.unibo.javadyno.model.dyno.simulated.api;

/**
 * Interface used to realized to model temperature variation in an Engine.
 */
public interface TemperatureModel {
    /**
     * update of temperature model by deltaTime.
     *
     * @param generatedPower power generated by the engine [W]
     * @param ambientTemp ambient temperature [°C]
     * @param deltaTime elapsed time of simulation step [s]
     */
    void update(double generatedPower, double ambientTemp, double deltaTime);

    /**
     * getter for engine temperature.
     *
     * @return engine temperature [°C]
     */
    double getTemperature();
}
